name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Copy files to the right path
        run: rsync --remove-source-files -r ./ /home/admin/web
      # - name: Build docker and run image
      #   working-directory: /home/admin/web
      #   run: docker compose up -d
      # - name: Clean up
      #   working-directory: /home/admin/web
      #   run: ls | grep -xvE ".env" | xargs rm -r
